### ISSUE TITLE
Have some way to check the websocket 

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#280]
1. We've seen some issues that are related to events - but events are flowing to an external UI connection (From my laptop) but the pi itself is not receiving them. it would be nice to check the state of the websocket.

**Comment by dannyrandall** [comment]
https://github.com/byuoitav/touchpanel-ui-microservice/commit/decb4b005ba6652324dd1708c12de227ee51c002

Can now send a PUT request to `/socketTest` and it will put a notification onto the screen if the websocket is open.
