### ISSUE TITLE
Blanking in shared mode is weird

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#284]
the commands themselves work. But the blanked state on the pi's doesn't always reflect that.

**Comment by xuther** [comment]
We are separating control and state. 

Currently we were saying that if any display in a group is unblanked, the 'group' input is unblanked. They want the blanked state to only reflect the 'connected' screen.

**Comment by dannyrandall** [comment]
On the controlling pi, or on the controlled pis? Or both?

**Comment by dannyrandall** [comment]
Do they want the blank button to affect all of the displays that have been shared to?

**Comment by xuther** [comment]
Blanked is to affect all controlled screens. But if another screen moves away from blanked (even if on the shared input) the state of that button only reflects the 'connected' screen.

**Comment by xuther** [comment]
That's also desired to be true for associated inputs. If there's a conflict of state within the group - we default to the 'connected' display (so D1 for CP1).

**Comment by dannyrandall** [comment]
Closing issue due to new way we handle share. Blanking affects all controlled screens, and the state is reflected the same way. However, the displays the are being shared to can no longer deviate from the 'master' state, so the state will be reflected according to the current desires.
