### ISSUE TITLE
The sharing 'master' does not have control of the room wide audio when sharing

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#288]

**Comment by dannyrandall** [comment]
I don't believe it's supposed to control the room wide audio except when it shares to one of the "main" displays. Does it not control the room wide audio even if it shares to one of the "main" displays?

**Comment by xuther** [comment]
right - so if D1 is the room-wide audio. and I share including that space. The "sharer's" audio mutes, but the D1 panel's audio doesn't. 

Eventually what happens on D1 doesn't matter (due to the modal) - but the group 'master' needs to have control of the volume - right now it's still controlling the display associated with that panel's audio.

**Comment by dannyrandall** [comment]
Should be fixed by #296, I'll wait to close the issue until that is verified.
