### ISSUE TITLE
Resolve dependency vulnerabilities - handlebars.js

### ISSUE THREAD

**Issue by danclegg** [byuoitav/touchpanel-ui-microservice#364]
handlebars.js is reported as having a vulnerability in our deployed version. More info: https://github.com/byuoitav/touchpanel-ui-microservice/network/dependencies#596035

**Comment by dannyrandall** [comment]
Fixed in 58aaa3d78e17524c9549ed18256f35ba2d2619f2 by upgrading `@angular-cli` to `1.5.3` from `1.5.0`.
