### ISSUE TITLE
Add ability to have panels mirror

### ISSUE THREAD

**Issue by dannyrandall** [byuoitav/touchpanel-ui-microservice#365]
This directly applies to the pi's in the back of the HCEB-BALLRM. We need the ability to have a panel in the back mirroring (always display the same thing) as the one in the front.

**Comment by dannyrandall** [comment]
The code to do this is currently in testing, we now need the business team to validate that everything is working correctly before pushing it out to campus.

**Comment by xuther** [comment]
Done, merged into stage as PR #368
