### ISSUE TITLE
Front End (client) retry socket connection

### ISSUE THREAD

**Issue by xuther** [byuoitav/touchpanel-ui-microservice#98]
We need to find a way to do 2 things. 

1) Have the front end try getting a socket connection until it's successful. If the socket is closed, it needs to continually try to reopen it until it can. 
2) Have some way to send a message up the socket telling the WebUI to refresh itself.

**Comment by dannyrandall** [comment]
2. Once the subscriber is ready, send a refresh message. 
2. Add an endpoint (for remote refresh) that sends a message down the socket with eventinfokey = refresh.
